apiVersion: apps/v1
kind: Deployment
metadata:
  name: BoundedContext629
  labels:
    app: BoundedContext629
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BoundedContext629
  template:
    metadata:
      labels:
        app: BoundedContext629
    spec:
      containers:
        - name: BoundedContext629
          image: username/BoundedContext629:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
